// <auto-generated />
using System;
using FirstWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstWeb.Data.Migrations.MetroBus
{
    [DbContext(typeof(MetroBusContext))]
    [Migration("20260307091505_InitialMetroBus")]
    partial class InitialMetroBus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstWeb.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BoardingStop")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DestinationStop")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumberOfPassengers")
                        .HasColumnType("int");

                    b.Property<string>("PassengerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PassengerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalFare")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BookingId");

                    b.HasIndex("RouteId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("FirstWeb.Models.BusRoute", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<string>("BusColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("EstimatedTimeMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("Fare")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FromStation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OperatingHours")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RouteCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ToStation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalStops")
                        .HasColumnType("int");

                    b.HasKey("RouteId");

                    b.ToTable("BusRoutes");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            BusColor = "#DC2626",
                            Description = "The Red Line connects Saddar Rawalpindi to Islamabad Secretariat, passing through major commercial areas and government offices. Air-conditioned buses with comfortable seating.",
                            DistanceKm = 22.5,
                            EstimatedTimeMinutes = 45,
                            Fare = 50m,
                            Frequency = "Every 10 minutes",
                            FromStation = "Saddar",
                            IsActive = true,
                            OperatingHours = "6:00 AM - 10:00 PM",
                            RouteCode = "RED",
                            RouteName = "Red Line - Rawalpindi Metro",
                            ToStation = "Islamabad Secretariat",
                            TotalStops = 12
                        },
                        new
                        {
                            RouteId = 2,
                            BusColor = "#2563EB",
                            Description = "The Blue Line runs through the heart of Islamabad, connecting Faizabad to Faisal Mosque via major landmarks including Jinnah Avenue and the Blue Area commercial district.",
                            DistanceKm = 18.0,
                            EstimatedTimeMinutes = 35,
                            Fare = 50m,
                            Frequency = "Every 12 minutes",
                            FromStation = "Faizabad",
                            IsActive = true,
                            OperatingHours = "6:00 AM - 10:30 PM",
                            RouteCode = "BLUE",
                            RouteName = "Blue Line - Islamabad Express",
                            ToStation = "Faisal Mosque",
                            TotalStops = 10
                        },
                        new
                        {
                            RouteId = 3,
                            BusColor = "#EA580C",
                            Description = "The Orange Line provides direct connectivity from Rawalpindi Railway Station to the New Islamabad International Airport, serving commuters and travelers with premium service.",
                            DistanceKm = 35.0,
                            EstimatedTimeMinutes = 55,
                            Fare = 80m,
                            Frequency = "Every 15 minutes",
                            FromStation = "Rawalpindi Railway Station",
                            IsActive = true,
                            OperatingHours = "5:00 AM - 11:00 PM",
                            RouteCode = "ORANGE",
                            RouteName = "Orange Line - Airport Connector",
                            ToStation = "Islamabad International Airport",
                            TotalStops = 14
                        },
                        new
                        {
                            RouteId = 4,
                            BusColor = "#16A34A",
                            Description = "The Green Line serves the scenic route along Margalla Hills foothill, connecting Pirwadhai bus terminal to Centaurus Mall, passing through residential and commercial zones of Islamabad.",
                            DistanceKm = 16.0,
                            EstimatedTimeMinutes = 30,
                            Fare = 40m,
                            Frequency = "Every 8 minutes",
                            FromStation = "Pirwadhai",
                            IsActive = true,
                            OperatingHours = "6:00 AM - 10:00 PM",
                            RouteCode = "GREEN",
                            RouteName = "Green Line - Margalla Express",
                            ToStation = "Centaurus Mall",
                            TotalStops = 11
                        });
                });

            modelBuilder.Entity("FirstWeb.Models.BusStop", b =>
                {
                    b.Property<int>("StopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StopId"));

                    b.Property<string>("Area")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("StopName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int");

                    b.HasKey("StopId");

                    b.HasIndex("RouteId");

                    b.ToTable("BusStops");

                    b.HasData(
                        new
                        {
                            StopId = 1,
                            Area = "Saddar, Rawalpindi",
                            RouteId = 1,
                            StopName = "Saddar",
                            StopOrder = 1
                        },
                        new
                        {
                            StopId = 2,
                            Area = "Committee Chowk, Rawalpindi",
                            RouteId = 1,
                            StopName = "Committee Chowk",
                            StopOrder = 2
                        },
                        new
                        {
                            StopId = 3,
                            Area = "Liaquat Bagh, Rawalpindi",
                            RouteId = 1,
                            StopName = "Liaquat Bagh",
                            StopOrder = 3
                        },
                        new
                        {
                            StopId = 4,
                            Area = "Marrir Chowk, Rawalpindi",
                            RouteId = 1,
                            StopName = "Marrir Chowk",
                            StopOrder = 4
                        },
                        new
                        {
                            StopId = 5,
                            Area = "Satellite Town, Rawalpindi",
                            RouteId = 1,
                            StopName = "6th Road",
                            StopOrder = 5
                        },
                        new
                        {
                            StopId = 6,
                            Area = "Rehmanabad, Rawalpindi",
                            RouteId = 1,
                            StopName = "Rehmanabad",
                            StopOrder = 6
                        },
                        new
                        {
                            StopId = 7,
                            Area = "Chandni Chowk, Rawalpindi",
                            RouteId = 1,
                            StopName = "Chandni Chowk",
                            StopOrder = 7
                        },
                        new
                        {
                            StopId = 8,
                            Area = "Faizabad, Rawalpindi",
                            RouteId = 1,
                            StopName = "Faizabad",
                            StopOrder = 8
                        },
                        new
                        {
                            StopId = 9,
                            Area = "IJP Road, Rawalpindi",
                            RouteId = 1,
                            StopName = "IJP Road",
                            StopOrder = 9
                        },
                        new
                        {
                            StopId = 10,
                            Area = "Potohar Town, Rawalpindi",
                            RouteId = 1,
                            StopName = "Potohar Town",
                            StopOrder = 10
                        },
                        new
                        {
                            StopId = 11,
                            Area = "Secretariat, Islamabad",
                            RouteId = 1,
                            StopName = "Pakistan Secretariat",
                            StopOrder = 11
                        },
                        new
                        {
                            StopId = 12,
                            Area = "Secretariat, Islamabad",
                            RouteId = 1,
                            StopName = "Islamabad Secretariat",
                            StopOrder = 12
                        },
                        new
                        {
                            StopId = 13,
                            Area = "Faizabad, Rawalpindi",
                            RouteId = 2,
                            StopName = "Faizabad",
                            StopOrder = 1
                        },
                        new
                        {
                            StopId = 14,
                            Area = "Shamsabad, Rawalpindi",
                            RouteId = 2,
                            StopName = "Shamsabad",
                            StopOrder = 2
                        },
                        new
                        {
                            StopId = 15,
                            Area = "I-8, Islamabad",
                            RouteId = 2,
                            StopName = "I-8 Markaz",
                            StopOrder = 3
                        },
                        new
                        {
                            StopId = 16,
                            Area = "Aabpara, Islamabad",
                            RouteId = 2,
                            StopName = "Aabpara",
                            StopOrder = 4
                        },
                        new
                        {
                            StopId = 17,
                            Area = "Blue Area, Islamabad",
                            RouteId = 2,
                            StopName = "Blue Area (Jinnah Ave)",
                            StopOrder = 5
                        },
                        new
                        {
                            StopId = 18,
                            Area = "G-6, Islamabad",
                            RouteId = 2,
                            StopName = "Melody Market",
                            StopOrder = 6
                        },
                        new
                        {
                            StopId = 19,
                            Area = "F-6, Islamabad",
                            RouteId = 2,
                            StopName = "Super Market (F-6)",
                            StopOrder = 7
                        },
                        new
                        {
                            StopId = 20,
                            Area = "F-7, Islamabad",
                            RouteId = 2,
                            StopName = "F-7 Markaz",
                            StopOrder = 8
                        },
                        new
                        {
                            StopId = 21,
                            Area = "E-7, Islamabad",
                            RouteId = 2,
                            StopName = "E-7 Sector",
                            StopOrder = 9
                        },
                        new
                        {
                            StopId = 22,
                            Area = "E-7, Islamabad",
                            RouteId = 2,
                            StopName = "Faisal Mosque",
                            StopOrder = 10
                        },
                        new
                        {
                            StopId = 23,
                            Area = "Saddar, Rawalpindi",
                            RouteId = 3,
                            StopName = "Rawalpindi Railway Station",
                            StopOrder = 1
                        },
                        new
                        {
                            StopId = 24,
                            Area = "Satellite Town, Rawalpindi",
                            RouteId = 3,
                            StopName = "Commercial Market",
                            StopOrder = 2
                        },
                        new
                        {
                            StopId = 25,
                            Area = "Shamsabad, Rawalpindi",
                            RouteId = 3,
                            StopName = "Shamsabad",
                            StopOrder = 3
                        },
                        new
                        {
                            StopId = 26,
                            Area = "Faizabad, Rawalpindi",
                            RouteId = 3,
                            StopName = "Faizabad",
                            StopOrder = 4
                        },
                        new
                        {
                            StopId = 27,
                            Area = "Pirwadhai, Rawalpindi",
                            RouteId = 3,
                            StopName = "Pirwadhai Mor",
                            StopOrder = 5
                        },
                        new
                        {
                            StopId = 28,
                            Area = "I-9, Islamabad",
                            RouteId = 3,
                            StopName = "I-9 Industrial Area",
                            StopOrder = 6
                        },
                        new
                        {
                            StopId = 29,
                            Area = "I-10, Islamabad",
                            RouteId = 3,
                            StopName = "I-10 Markaz",
                            StopOrder = 7
                        },
                        new
                        {
                            StopId = 30,
                            Area = "I-11, Islamabad",
                            RouteId = 3,
                            StopName = "I-11 Sector",
                            StopOrder = 8
                        },
                        new
                        {
                            StopId = 31,
                            Area = "I-14, Islamabad",
                            RouteId = 3,
                            StopName = "I-14 Sector",
                            StopOrder = 9
                        },
                        new
                        {
                            StopId = 32,
                            Area = "I-16, Islamabad",
                            RouteId = 3,
                            StopName = "I-16 Sector",
                            StopOrder = 10
                        },
                        new
                        {
                            StopId = 33,
                            Area = "Taxila, Rawalpindi",
                            RouteId = 3,
                            StopName = "Taxila Bypass",
                            StopOrder = 11
                        },
                        new
                        {
                            StopId = 34,
                            Area = "Tarnol, Islamabad",
                            RouteId = 3,
                            StopName = "Tarnol",
                            StopOrder = 12
                        },
                        new
                        {
                            StopId = 35,
                            Area = "Golra, Islamabad",
                            RouteId = 3,
                            StopName = "Golra Mor",
                            StopOrder = 13
                        },
                        new
                        {
                            StopId = 36,
                            Area = "Airport, Islamabad",
                            RouteId = 3,
                            StopName = "Islamabad International Airport",
                            StopOrder = 14
                        },
                        new
                        {
                            StopId = 37,
                            Area = "Pirwadhai, Rawalpindi",
                            RouteId = 4,
                            StopName = "Pirwadhai",
                            StopOrder = 1
                        },
                        new
                        {
                            StopId = 38,
                            Area = "Satellite Town, Rawalpindi",
                            RouteId = 4,
                            StopName = "6th Road Chowk",
                            StopOrder = 2
                        },
                        new
                        {
                            StopId = 39,
                            Area = "Murree Road, Rawalpindi",
                            RouteId = 4,
                            StopName = "Murree Road",
                            StopOrder = 3
                        },
                        new
                        {
                            StopId = 40,
                            Area = "Faizabad, Rawalpindi",
                            RouteId = 4,
                            StopName = "Faizabad",
                            StopOrder = 4
                        },
                        new
                        {
                            StopId = 41,
                            Area = "Margalla Hills, Islamabad",
                            RouteId = 4,
                            StopName = "Pir Sohawa Road",
                            StopOrder = 5
                        },
                        new
                        {
                            StopId = 42,
                            Area = "F-10, Islamabad",
                            RouteId = 4,
                            StopName = "F-10 Markaz",
                            StopOrder = 6
                        },
                        new
                        {
                            StopId = 43,
                            Area = "F-8, Islamabad",
                            RouteId = 4,
                            StopName = "F-8 Markaz",
                            StopOrder = 7
                        },
                        new
                        {
                            StopId = 44,
                            Area = "F-7, Islamabad",
                            RouteId = 4,
                            StopName = "F-7 Markaz",
                            StopOrder = 8
                        },
                        new
                        {
                            StopId = 45,
                            Area = "F-7, Islamabad",
                            RouteId = 4,
                            StopName = "Jinnah Super Market",
                            StopOrder = 9
                        },
                        new
                        {
                            StopId = 46,
                            Area = "Blue Area, Islamabad",
                            RouteId = 4,
                            StopName = "Blue Area",
                            StopOrder = 10
                        },
                        new
                        {
                            StopId = 47,
                            Area = "F-8, Islamabad",
                            RouteId = 4,
                            StopName = "Centaurus Mall",
                            StopOrder = 11
                        });
                });

            modelBuilder.Entity("FirstWeb.Models.Booking", b =>
                {
                    b.HasOne("FirstWeb.Models.BusRoute", "Route")
                        .WithMany("Bookings")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("FirstWeb.Models.BusStop", b =>
                {
                    b.HasOne("FirstWeb.Models.BusRoute", "Route")
                        .WithMany("Stops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("FirstWeb.Models.BusRoute", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
